name: Build Workflow
on: push

jobs:
  build:
    name: Build main site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: build
