name: Build Workflow
on: push

jobs:
  build:
    name: Build main site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: build
      - name: Deploy to gh-pages
      - uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./public
